### ISSUE TITLE
Hope there has a option to set the proxy for the capture traffic network to pass through

### ISSUE THREAD

**Issue by xywwf** [sigoden/proxyfor#41]

**Comment by sigoden** [comment]
We don't understand what you mean.

**Comment by xywwf** [comment]
> I don't understand what you mean.
> 
> If you don't want your traffic to be recorded, you can use `--filters` / `--mime-filters`.

I want proxyfor use other proxy address to visit the web

**Comment by sigoden** [comment]
Now I understand. There are no plans to support it.
